spring.application.name=Coffee Sales Backend

#Port
#port =

#Postgresql Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/coffeesalesdb
spring.datasource.username=coffee
spring.datasource.password=coffee
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Cors Configuration
spring.web.cors.allowed-origins=http://localhost:5173

#JWT Configuration
#JWT_SECRET=nvienuiehuio123njkunoc940183hugb21u2h9fun1uv9nuinwvi2-19
#jwt.secret = ${JWT_SECRET:dev-secret-key-for-local-testing-32-chars}
#Admin password: CoffeeAdminIsJohn!08052025
jwt.secret = ${JWT_SECRET}
jwt.expiration=3600000
jwt.admin_expiration= 36000000

#TRACE LOGGING, Enable if needed
#logging.level.org.springframework.security: TRACE

#Disable spring auto config in-memory user
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

#Rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest